version: '3.9'
services:
  mongodatabase1:
    image: mongo:6.0.3
    container_name: mongodatabase1
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mongo-dev